version: "3.9"

services:

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    ports:
      - "3001:3001"

  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
